Potential functions method
andriygav/MLbook pull request #18
Opened 2024-12-02 22:53 UTC by d3phys

Тема: Метрические методы классификации и регрессии
Подтема: Метод потенциальных функций

Дедков Денис Андреевич Б01-108

Подправил структурно главу про метрические методы:
- Перенес секцию про KNN в chapters/metric/knn.tex
- Вставил секцию про Парзеновское окно chapters/metric/Parzen_window.tex

2024-12-09 07:31 UTC, andriygav requested changes
1. Все должно быть в файле main.tex
2. Нет файла Parzen_window.tex
3. Конфликты

2024-12-09 18:18 UTC, d3phys commented
> 1. Все должно быть в файле main.tex
> 2. Нет файла Parzen_window.tex
> 3. Конфликты

Вот же он. Мне перенести его в main?
https://github.com/andriygav/MLbook/blob/master/chapters/metric/Parzen_window.tex

2024-12-10 15:33 UTC, andriygav commented
Все должно быть в main.tex. Я видимо где-то недосмотрел

2024-12-11 18:34 UTC, d3phys commented
- Перенес potential_functions.tex в main.tex
- Перенес Parzen_window.tex в main.tex

Теперь в chapters/metric всё как везде.

2024-12-13 09:24 UTC, andriygav approved these changes

2024-12-13 09:24 UTC, merged