Added chapter about semi supervised learning
andriygav/MLbook pull request #19
Opened 2024-12-03 11:33 UTC by GammaTwoGames

2024-12-09 07:29 UTC, andriygav requested changes
1. Нужно изменить название файла на main.tex (и разрешить конфликты если будут)

2024-12-10 09:26 UTC, GammaTwoGames commented
Сделал

2024-12-10 15:33 UTC, andriygav commented
ssl.tex все еще не подгружается в общий файл.

2024-12-10 15:34 UTC, andriygav commented
Все еще есть document class и тд, которых быть не должно. Это глава общего сборника, а не отдельный сьорник

2024-12-11 07:08 UTC, GammaTwoGames commented
Добавил содержимое ssl в main, как глава, а не отдельный файл

2024-12-13 09:25 UTC, andriygav approved these changes

2024-12-13 09:25 UTC, merged