Персептрон, BackProp, обычный и стохастический градиенты
andriygav/MLbook pull request #2
Opened 2024-11-03 13:02 UTC by ArtemMaslov

Полносвязная нейронная сеть (Персептрон). Метод обратного распространения ошибок. Обычный и стохастический градиентные спуски для персептрона.

Маслов Артём, Б01-108а.

2024-11-05 11:13 UTC, andriygav requested changes

2024-11-05 11:13 UTC, andriygav commented on main.pdf
Файл pdf убрать

2024-11-05 12:19 UTC, ArtemMaslov commented on main.pdf
Убрал

2024-11-07 09:29 UTC, andriygav approved these changes

2024-11-12 08:02 UTC, merged