Add files via upload
andriygav/MLbook pull request #28
Opened 2024-12-09 08:55 UTC by sdjenjer

Added zip-archive of Overleaf with the text

2024-12-09 11:04 UTC, andriygav requested changes
не совсем понимаю зачем сюда зип архив. нужно внести все изменения в файлы.

2024-12-10 09:25 UTC, sdjenjer commented
Я вроде бы внёс изменения в файлы тоже, но сейчас их не вижу. Можете проверить, пожалуйста, Вам их видно? Сто лет гитом не пользовался, не помню, как там правильно делать пуллреквесты

2024-12-10 15:37 UTC, andriygav commented
Все что вижу, только zip архив

2024-12-10 15:44 UTC, sdjenjer commented
У меня там сейчас другой пулл реквест висит, в нём по идее должно быть видно

2024-12-11 05:10 UTC, closed without merging