Елена Земскова. Неразмеченные данные в глубоком обучении
andriygav/MLbook pull request #29
Opened 2024-12-09 11:18 UTC by HelenaZemskova

2024-12-10 15:38 UTC, andriygav commented
Требуется убрать все что связано с documentclass. Это глава, а не отдельный файл

2024-12-10 15:39 UTC, andriygav requested changes
Убрать лишние строки

2024-12-12 17:08 UTC, HelenaZemskova commented
Изменения внесла

2024-12-13 09:26 UTC, andriygav approved these changes

2024-12-13 09:26 UTC, merged