Sdjenjer patch 1
andriygav/MLbook pull request #39
Opened 2024-12-10 10:38 UTC by sdjenjer

Переместил и поправил текст из оверлифа в general/main. Убрал из linear/main

2024-12-10 15:46 UTC, andriygav requested changes
Конфликты

2024-12-10 16:11 UTC, sdjenjer commented
Поправил

2024-12-11 05:10 UTC, andriygav requested changes
При исправлении конфликтов вы удалили целую главу другого человека

2024-12-11 06:32 UTC, sdjenjer commented
Мне значит новый пуллреквест сделать? Не понимаю, как ещё можно убрать конфликты здесь

2024-12-11 11:47 UTC, closed without merging