dbscan chapter added
andriygav/MLbook pull request #40
Opened 2024-12-10 14:17 UTC by KozlovNA

2024-12-10 15:48 UTC, andriygav requested changes
Должна быть глава, а не документ

2024-12-10 16:55 UTC, KozlovNA commented
поправил

2024-12-11 05:11 UTC, andriygav approved these changes

2024-12-11 05:11 UTC, merged

2024-12-15 16:25 UTC, KozlovNA commented
Козлов Николай Б05-101а
kozlov.na@phystech.edu