Add tasks on the LDA topic
andriygav/MLbook pull request #5
Opened 2024-11-19 19:08 UTC by Agustangel

Глава 2: Линейные методы классификации и регрессии
Подтема: Линейный дискриминантный анализ (LDA).

Мельникова Юлия Владимировна Б01-108

2024-11-21 14:09 UTC, andriygav approved these changes

2024-11-21 14:10 UTC, andriygav requested changes
Требуется изменить название файла на main.tex

2024-12-04 15:52 UTC, Agustangel commented
Не могу, файл с таким именем уже существует в директории

2024-12-09 07:33 UTC, andriygav commented
Нужно внести в файл main.tex весь ваш текст и исправить конфликты. Ваш файл не подтянется сборником

2024-12-15 07:51 UTC, merged